name: Build
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: nightly-2025-04-22
      - name: Install cargo-sort from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort
      - run: sudo apt-get install protobuf-compiler -y
      - run: cargo sort --workspace --check
      - run: cargo fmt --all --check
      - run: cargo +nightly-2025-04-22 clippy --all-features --all-targets --tests -- -A clippy::err-expect -A dead-code -D warnings
  verified_build:
    name: verified_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-04-22
      - name: Install solana-verify from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: solana-verify
          version: "0.4.0"
      - name: install solana toolsuite
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.18.26/install)"
      - name: add to path
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - run: solana-verify build --library-name stake_deposit_interceptor
      - name: Upload program artifact
        uses: actions/upload-artifact@v4
        with:
          name: program.so
          path: target/deploy/*.so
  test:
    name: test
    runs-on: ubuntu-latest
    needs:
      - verified_build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: sudo apt-get install protobuf-compiler -y
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-04-22
      - name: cargo test
        run: cargo test --all-features --color auto
        shell: bash
        env:
          RUST_LOG: trace
          SBF_OUT_DIR: ${{ github.workspace }}/target/deploy
          RUST_MIN_STACK: 10000000
