name: Build
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: "1.85.0"
      - name: Install cargo-sort from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort
      - run: sudo apt-get install protobuf-compiler -y
      - run: cargo sort --workspace --check
      - run: cargo fmt --all --check
      - run: cargo clippy --all-features --all-targets --tests -- -D warnings

  verified_build:
    name: verified_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install solana-verify deps
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libudev-dev libclang-dev
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85.0"
      - name: Install solana-verify from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: solana-verify
          version: "0.4.11"
      - name: install solana toolsuite
        run: sh -c "$(curl -sSfL https://release.anza.xyz/v2.2.1/install)"
      - name: add to path
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - run: solana-verify build --library-name stake_deposit_interceptor
      - name: Upload program artifact
        uses: actions/upload-artifact@v4
        with:
          name: program.so
          path: target/deploy/*.so
